### ISSUE TITLE
CSS engine needs work

### ISSUE THREAD

**Issue by monokee** [monokee/Cue#6]
Complex selection is not working as expected.
For example:

```css
self:hover refName {
  color: red;
}
```

is not converted to

```css
my-component:hover [ref="refName"] {
  color: red;
}
```

and there are likely more bugs and quirks.

**Comment by monokee** [comment]
by using shorthand selectors for refs we might introduce a lot of overhead for the parser because we need to keep track of all existing refs and internally compare them against other tagNames to prevent name clashes. How should we handle:

```html
<canvas ref="canvas"></canvas>
```
Does "canvas" in our component css refer to the ref or the tag?

```css
canvas {
  position: absolute;
}
```
